version: 2
# refresh: 20240521-2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
      - "gh-workflows"
    commit-message:
      prefix: "ci: [dependabot] " # extra whitespace to avoid second ":" in the commit message

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
      - "npm"
    commit-message:
      prefix: "ci: [dependabot] " # extra whitespace to avoid second ":" in the commit message
    groups:
      npm-dependencies:
        patterns:
          - "*"
    ignore:
      # keep dependencies used by the GH action (check action.yml) out of the updates
      - dependency-name: "ajv"
      - dependency-name: "core-js"
      - dependency-name: "js-yaml"
      - dependency-name: "nunjucks"

  # - package-ecosystem: "npm"
  #   directory: "/cypress/"
  #   schedule:
  #     interval: "monthly"
  #   labels:
  #     - "dependabot"
  #     - "npm-cypress"
  #   commit-message:
  #     prefix: "ci: [dependabot] " # extra whitespace to avoid second ":" in the commit message
  #   groups:
  #     npm-dependencies:
  #       patterns:
  #         - "*"
