version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
      - "gh-workflows"
    commit-message:
      prefix: "ci: [dependabot]"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
      - "npm"
    commit-message:
      prefix: "ci: [dependabot]"

  - package-ecosystem: "npm"
    directory: "/cypress/"
    schedule:
      interval: "monthly"
    labels:
      - "dependabot"
      - "npm-cypress"
    commit-message:
      prefix: "ci: [dependabot]"
