version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot/github-actions"

  - package-ecosystem: "github-actions"
    directory: "/action.yml"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot/github-actions"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot/npm"

  - package-ecosystem: "npm"
    directory: "/cypress/"
    schedule:
      interval: "monthly"
    labels:
      - "dependabot/npm-cypress"
