type: object
properties:
  commits:
    type: array
    description: |
      The list of commit types and their corresponding release types.
    default:
    - type: break
      release: major
    - type: feat
      release: minor
    - type: fix
      release: patch
    - type: revert
      release: patch
    - type: refactor
      release: none      
    - type: chore
      release: none
    - type: test
      release: none
    - type: docs
      release: none
    - type: ci
      release: none
    uniqueItems: true
    items:
      type: object
      properties:
        type:
          type: string
          examples: [break, feat, fix, revert, refactor, chore, test, docs, ci]
        release:
          type: string
          enum: [major, minor, patch, none]
      required:
        - type
        - release

  scopes:
    type: array
    description: |
      The list of scopes that can be used in commit messages.
    uniqueItems: true
    default: []
    items:
      type: object
      properties:
        key:
          type: string
          description: |
            "key provided in the commit messages example: 'feat(core): add new feature'"
        versioning:
          type: object
          description: |
            The versioning configuration for the scope.
          properties:
            file:
              type: string
              description: |
                JSON file where the version is stored
            changelog:
              type: string
              description: |
                markdown file where the changelog is stored
required:
  - commits
