type: object

required:
  - commits

properties:
  commits:
    type: array
    description: The list of commit types and their corresponding release types.
    default:
    - type: break
      release: major
    - type: feat
      release: minor
    - type: fix
      release: patch
    - type: revert
      release: patch
    - type: refactor
      release: none      
    - type: chore
      release: none
    - type: test
      release: none
    - type: docs
      release: none
    - type: ci
      release: none
    uniqueItems: true
    items:
      type: object
      properties:
        type:
          type: string
          examples: [break, feat, fix, revert, refactor, chore, test, docs, ci]
        release:
          type: string
          enum: [major, minor, patch, none]
      required:
        - type
        - release
  scopes:
    type: object
    required:
      - list
    default:
      create-gh-release: false
      print-summary: false
      list: []
    description: Scope configuration 
    properties:
      tag-version:
        type: boolean
        description: flag to tag the release commit with all the scopes affected
        default: true
      create-gh-release:
        type: boolean
        description: flag to create a github release for all the scopes
        default: false
      print-summary:
        type: boolean
        description: flag to print the release summary for all the scopes
        default: false
      list:
        type: array
        description: The scopes list
        uniqueItems: true
        items:
          type: object
          properties:
            key:
              type: string
              description: "The scope key provided in the commit message. Example: `feat(scope): message`"
            versioning:
              type: object
              description: The versioning configuration for the scope.
              properties:
                file:
                  type: string
                  description: JSON file where the version is stored
                changelog:
                  type: string
                  description: changelog markdown file
                tag-version:
                  type: boolean
                  description: flag to tag the release commit for this scope
                create-gh-release:
                  type: boolean
                  description: flag to create a github release for this scope
              required:
                - file
                - changelog
          required:
            - key
            - versioning


