name: 🏷️ Pull Request Labeler
on:
  pull_request:
    branches: ["main"]
    paths:
      - ".github/*"

concurrency:
  group: label-${{ github.head_ref  || github.ref_name }}"
  cancel-in-progress: true

permissions: read-all

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          configuration-path: .github/labeler.yml
