name: shared-get-changes

on:
  workflow_call:
    outputs:
      js-modified:
        value: ${{ jobs.get-changes.outputs.js-modified }}
      action-modified:
        value: ${{ jobs.get-changes.outputs.action-modified }}

permissions: read-all

jobs:
  get-changes:
    name: 🔎 Get Changes
    runs-on: ubuntu-latest
    outputs:
      js-modified: ${{ steps.changes.outputs.js }}
      action-modified: ${{ steps.changes.outputs.action }}
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Paths Changes Filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            js:
              - functions/**
              - plugins/**
              - package.json
              - package-lock.json
              - tests/index/**
              - tests/functions/**
            action:
              - action.yml
              - functions/**
              - plugins/**
              - cypress/**
              - package.json
              - package-lock.json
